server:
  port: 8080


###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/example/demo3/mapper/*.xml
  typeAliasesPackage: com.example.demo3.pojo
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性


spring:
  datasource:
    url: jdbc:sqlserver://120.24.56.105:1433;databasename=CarStop
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: lqb
    password: liuqingbo
